### PR TITLE
Issue#669 bad page number parameters causing ArgumentError

### LINKED ISSUE #669: Bad page number parameters cause ArgumentError to be raised
https://www.planningalerts.org.au/?page=2[&q=George+Street%2C+Redfern+NSW
## Backtrace

```
line 18 of [PROJECT_ROOT]/app/controllers/applications_controller.rb: index
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37075/faults/5869537)

### PR DESCRIPTION
**Pull request by hisayohorie**
Fixes #669.

I wrote 2 test for this method because
when the string passed starts with integer, to_i returns the same integer (ex. "2K%&)".to_i = 2) 
and other time it returns 0 (ex. "%&43{".to_i = 0)

and I'm not super sure this is the appropriate way to do it? please let me know!
@equivalentideas @henare

### CODE REVIEW

**Comment by hisayohorie** [comment]
@henare sure! I will look into it!

**Comment by hisayohorie** [comment]
@henare this is the discussion around the issue, and seems the best practice isn't solidified? 
https://github.com/mislav/will_paginate/issues/271

**Comment by henare** [comment]
@hisayohorie nice one on tracking down that discussion. That makes me :+1: this solution then.

I think we should add a comment above that method so people know why we've added it. You could even include a link to that discussion. Presumably when it's resolved upstream we'll be able to remove this workaround :sparkles: 

Once that's done let's merge and :shipit:

**Comment by henare** [comment]
@hisayohorie I noticed you updated this so I thought I'd give it a more thorough check.

>Once that's done let's merge and :shipit:

OK I got a bit ahead of myself :smile: I'll add a couple of comments :speech_balloon:

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -45,4 +45,14 @@ def ssl_required?
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :organisation])
   end
+
+  # this method is to respond to the will_paginate bug of invalid page number leading to error being thrown.
+  # see discussion here https://github.com/mislav/will_paginate/issues/271
+  def validate_page_param
+    unless params[:page].present? && params[:page].to_i > 0
```
Comment (henare) [inline app/controllers/application_controller.rb]: [Do not use unless with else. Rewrite these with the positive case first.](https://github.com/bbatsov/ruby-style-guide#no-else-with-unless)

I also notice your indentation is a little out on the params lines - you need an extra space.

File: spec/controllers/applications_controller_spec.rb [hunk 2]
```diff
@@ -15,6 +15,21 @@
         get :index
         expect(assigns[:rss]).to be_nil
       end
+
+      it "should try to convert page param to an integer" do
```
Comment (henare) [inline spec/controllers/applications_controller_spec.rb]: In my first review I didn't check where these tests were placed. They're under `#index rss feed` and since this isn't related to the RSS feed these tests should not be here.

But where should they go? I didn't know so I hunted around. I discovered that `ApplicationController` behaviour that does things like global error checking should be tested by [defining an anonymous controller](https://www.relishapp.com/rspec/rspec-rails/v/3-0/docs/controller-specs/anonymous-controller).

So create a new file in this directory called `application_controller_spec.rb`, with something like this (and removing the tests from this file):

```ruby
require "spec_helper"

describe ApplicationController do
  controller do
    def index
      render text: nil
    end
  end

  describe "#validate_page_param" do
    it "should try to convert page param to an integer" do
      get :index, page: "2%5B&q"

      expect(controller.params[:page]).to eq(2)
    end

    it "should default to page nil when no page number param is given" do
      get :index, page: "%5B&q"

      expect(controller.params[:page]).to eq(nil)
    end
  end
end
```

**Comment by henare** [comment]
@hisayohorie Once you're ready for me to take another look please assign back to me :handshake:

File: spec/controllers/applications_controller_spec.rb (hunk 2 above)
Comment (hisayohorie) [inline spec/controllers/applications_controller_spec.rb]: will do!

File: spec/controllers/applications_controller_spec.rb [hunk 3]
```diff
@@ -15,6 +15,7 @@
         get :index
         expect(assigns[:rss]).to be_nil
       end
+
```
Comment (henare) [inline spec/controllers/applications_controller_spec.rb]: Remove this stray extra line.

**Comment by henare** [comment]
Deployed :shipit:
